---
# Use container-based infrastructure
sudo: false

language: scala

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

jdk: oraclejdk7

scala: 2.11.6

script: "sbt clean test"

# Tricks to avoid unnecessary cache updates
before_cache:
  - find $HOME/.sbt -name "*.lock" -delete
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete

